### ISSUE TITLE
请教一个关于接口测试的问题

### ISSUE THREAD

**Issue by wangcityboy** [QihooTest/Leo#1]
请问你的xls文件的配置以及在addcase方法中添加的.class文件是怎么写的啊？

**Comment by wangcityboy** [comment]
问题补充，在编译方法中的四个参数中：分别如下：
JavaFile:/Users/apple/Downloads/Leo-master-whf/leo/ift/javaCase/InterfaceTest.java
DistPath:/Users/apple/Downloads/Leo-master-whf/target/classes/
LibPath:/Users/apple/Downloads/Leo-master-whf/lib/
JarFile:null

**Comment by QihooTest** [comment]
xls文件的配置在IftConf中进行配置的;.class文件怎么写？ 你可以下载example分支，为已写好的实例。

**Comment by wangcityboy** [comment]
请问接口测试中，上个接口测试返回的数据，其中一个字段作为下一个接口中的参数值，这个应该怎么处理。
